apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-dev
  template:
    metadata:
      labels:
        app: my-app-dev
    spec:
      containers:
        - name: my-app-dev
          image: my-app-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
